### ISSUE TITLE
地和判断问题

### ISSUE THREAD

**Issue by FrostHan** [Agony5757/mahjong#13]
庄家: Player 0
场风: 东
0本场 0立直棒
点数:25000|25000|25000|25000
牌山:9p4p8m4s0p6m3p5m8m4m4m9s4s3z9s0m5p8s4z2s2s2m1m7p8p8p3m2m1z1m7s7z4z3m2p6s4p5z2p5p6s9p4s8p6m6p0s4m3m2m7p4p7p6p3z7s9s4z5z3z1s2p8p4m6s6p2p7z1z3s6z5s5s7z1z4p5s3s7s3s9m6m1p5m4z4s9p7s6m5z2z7z2m8s7m9m5m2s3z3p6z9m7m2z3s2z8s7m6z8m1p8s1m3p1z2z1s6z3p1p7p7m1s1s3m5p6s9s9p9m6p1m8m1p5z2s
p0摸牌[7p]
p0手切[6m]
结果:荣和终局
Score:
Player 0:-7000
Player 1:25000
Player 2:25000
Player 3:57000
Player3:|地和|赤宝牌|宝牌||13番30符

**Comment by Agony5757** [comment]
Will be fixed in the next commit.
