### ISSUE TITLE
大佬 教我怎么用vs运行你的程序好不好

### ISSUE THREAD

**Issue by Ethic88** [Agony5757/mahjong#16]
错误	LNK2005	main 已经在 CMakeCXXCompilerId.obj 中定义

**Comment by Agony5757** [comment]
你是用VS的CMake打开的吗？
一般情况下，你可以看到MahjongTest.exe和MahjongPy.pyd两个target

**Comment by Ethic88** [comment]
编程懂得很少 vs也是第一次用 我的操作步骤是  从现有代码创建项目 选择了源码文件夹 其中项目类型选择的是Windows应用程序项目 一开始编译运行的时候 发现头文件没法包含 先是附加了包含目录 然后发现Mahjong/Yaku.h中std::string报错 又在Yaku.h中添加了#include <iostream> 接着就是上面提到的错误 不知道怎么解决了 然后您的源码运行后会有GUI吗 我好像没有发现这种功能 来自萌新的碎碎念 还请多多包涵

**Comment by Ethic88** [comment]
至于VS中的CMake 我感觉好像是编译时自动调用了 一点都不懂 瑟瑟发抖

**Comment by Agony5757** [comment]
没有做GUI。

VS Installer里面可以选安装CMake功能。如果成功安装的话，在
![QS6{6IXMAP UEJSR2{EX55N](https://user-images.githubusercontent.com/14315492/61521993-03d06d80-aa44-11e9-8b88-701e8845faca.png)
这里可以看到CMake的相关选项。

**Comment by Agony5757** [comment]
如果你成功安装了CMake，你可以在输出那里看到CMake缓存的信息。点击CMake，可以看到全部生成。
![图片](https://user-images.githubusercontent.com/14315492/61522172-69245e80-aa44-11e9-9892-d3a4fea39d25.png)
正在生成缓存

![图片](https://user-images.githubusercontent.com/14315492/61522197-780b1100-aa44-11e9-88d2-956352aa2ee9.png)
可以开始生成了。

![图片](https://user-images.githubusercontent.com/14315492/61522232-8bb67780-aa44-11e9-847c-997489cc1236.png)
输出信息
