### ISSUE TITLE
请问linux上要怎么make带中文字符的程序呢？

### ISSUE THREAD

**Issue by RuBP17** [Agony5757/mahjong#22]
它会报类似这样的错：
error: stray ‘\346’ in program
   22 |  p1���, p1河,
error: expected unqualified-id before ‘:’ token
   47 |  case Action::荣和:
      |                              ^

**Comment by icehehehe** [comment]
I think you should use GBK encoding.

**Comment by Agony5757** [comment]
> 它会报类似这样的错： error: stray ‘\346’ in program 22 | p1���, p1河, error: expected unqualified-id before ‘:’ token 47 | case Action::荣和: | 

用clang（推荐），或者用我最近的Remove-Unicode-Character分支（更新不一定及时）
