### ISSUE TITLE
代码中很多函数存在拷贝vector的情况

### ISSUE THREAD

**Issue by fangtiancheng** [Agony5757/mahjong#25]
作者您好！我在debug代码时，进入一个函数之前，老是进入std vector的alloc等库中。后来发现，函数在传参数的时候，大多数情况都是传的vector<T>，例如`Rule.cpp:get听牌()` `Table.cpp:game_init_for_replay()`等函数中都出现了这种情况。如果函数只需要读取vector<T>中的内容的话，建议您把参数改成const vector<T>&，这样省去了拷贝，代码运行起来会更快。

**Comment by Agony5757** [comment]
在改了在改了（

**Comment by Agony5757** [comment]
在release下这些可能会被编译器优化掉，不一定会造成拷贝。我的思路是暂时先保证正确性
